namespace BeatLeader_Server.Models
{
    public enum HMD
    {
        unknown = 0,
        rift = 1,
        riftS = 16,
        quest = 32,
        quest2 = 256,
        quest3 = 512,
        vive = 2,
        vivePro = 4,
        viveCosmos = 128,
        wmr = 8,

        picoNeo3 = 33,
        picoNeo2 = 34,
        vivePro2 = 35,
        viveElite = 36,
        miramar = 37,
        pimax8k = 38,
        pimax5k = 39,
        pimaxArtisan = 40,
        hpReverb = 41,
        samsungWmr = 42,
        qiyuDream = 43,
        disco = 44,
        lenovoExplorer = 45,
        acerWmr = 46,
        viveFocus = 47,
        arpara = 48,
        dellVisor = 49,
        e3 = 50,
        viveDvt = 51,
        glasses20 = 52,
        hedy = 53,
        vaporeon = 54,
        huaweivr = 55,
        asusWmr = 56,
        cloudxr = 57,
        vridge = 58,
        medion = 59,
        picoNeo4 = 60,
        questPro = 61,
        pimaxCrystal = 62,
        e4 = 63,
        index = 64,
        controllable = 65,
        bigscreenbeyond = 66,
        nolosonic = 67,
        hypereal = 68,
        varjoaero = 69
    }
}
